// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt7Negh9O6K9w1WdHEnJpwzUP6DWFMWoI',
    appId: '1:748615557905:web:02e396309dcbd6e66962b0',
    messagingSenderId: '748615557905',
    projectId: 'spotifyclonedb',
    authDomain: 'spotifyclonedb.firebaseapp.com',
    storageBucket: 'spotifyclonedb.appspot.com',
    measurementId: 'G-48GR2G83TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeGsK_KJOIHK3Tw_FuvgMrkRx-JdMDVR8',
    appId: '1:748615557905:android:eebfdf4dda0050376962b0',
    messagingSenderId: '748615557905',
    projectId: 'spotifyclonedb',
    storageBucket: 'spotifyclonedb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhozj7RDYck0jeQcl7xgiv5B4RNWSem7E',
    appId: '1:748615557905:ios:0b9772d11a3109266962b0',
    messagingSenderId: '748615557905',
    projectId: 'spotifyclonedb',
    storageBucket: 'spotifyclonedb.appspot.com',
    iosBundleId: 'com.spotify.clone',
  );
}
